# Generated by Django 6.0.3 on 2026-03-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_code', models.CharField(max_length=100, unique=True, verbose_name='DN单号')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总重量')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总体积')),
                ('dn_status', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': 'DN单',
                'verbose_name_plural': 'DN单',
                'db_table': 'dn_list',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_qty', models.IntegerField(default=0, verbose_name='计划数量')),
                ('pick_qty', models.IntegerField(default=0, verbose_name='拣货数量')),
                ('shipped_qty', models.IntegerField(default=0, verbose_name='发运数量')),
                ('goods_unit', models.CharField(max_length=50, verbose_name='单位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goods', verbose_name='商品')),
                ('dn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outbound.dnlist', verbose_name='DN单')),
            ],
            options={
                'verbose_name': 'DN明细',
                'verbose_name_plural': 'DN明细',
                'db_table': 'dn_detail',
                'ordering': ['-create_time'],
            },
        ),
    ]
