# Generated by Django 6.0.3 on 2026-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dndetail',
            name='pick_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='拣货数量'),
        ),
        migrations.AlterField(
            model_name='dndetail',
            name='plan_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='计划数量'),
        ),
        migrations.AlterField(
            model_name='dndetail',
            name='shipped_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='发运数量'),
        ),
    ]
