# Generated by Django 6.0.3 on 2026-03-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=200, verbose_name='仓库名称')),
                ('bin_name', models.CharField(max_length=100, verbose_name='货位名称')),
                ('goods_qty', models.IntegerField(default=0, verbose_name='库存数量')),
                ('goods_unit', models.CharField(max_length=50, verbose_name='商品单位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'stock',
                'ordering': ['-update_time'],
            },
        ),
    ]
