# Generated by Django 6.0.3 on 2026-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='goods_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='库存数量'),
        ),
    ]
