# Generated by Django 6.0.3 on 2026-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='员工姓名')),
                ('staff_type', models.CharField(max_length=50, verbose_name='员工类型')),
                ('staff_email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('staff_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'staff',
                'ordering': ['-create_time'],
            },
        ),
    ]
