# Generated by Django 6.0.3 on 2026-03-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsnList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asn_code', models.CharField(max_length=100, unique=True, verbose_name='ASN单号')),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总重量')),
                ('total_volume', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总体积')),
                ('asn_status', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': 'ASN单',
                'verbose_name_plural': 'ASN单',
                'db_table': 'asn_list',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AsnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_qty', models.IntegerField(default=0, verbose_name='预计数量')),
                ('actual_qty', models.IntegerField(default=0, verbose_name='实际数量')),
                ('sorted_qty', models.IntegerField(default=0, verbose_name='分拣数量')),
                ('goods_unit', models.CharField(max_length=50, verbose_name='单位')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.goods', verbose_name='商品')),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbound.asnlist', verbose_name='ASN单')),
            ],
            options={
                'verbose_name': 'ASN明细',
                'verbose_name_plural': 'ASN明细',
                'db_table': 'asn_detail',
                'ordering': ['-create_time'],
            },
        ),
    ]
