# Generated by Django 6.0.3 on 2026-03-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbound', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asndetail',
            name='actual_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='实际数量'),
        ),
        migrations.AlterField(
            model_name='asndetail',
            name='expected_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='预计数量'),
        ),
        migrations.AlterField(
            model_name='asndetail',
            name='sorted_qty',
            field=models.PositiveIntegerField(default=0, verbose_name='分拣数量'),
        ),
    ]
