# Generated by Django 6.0.3 on 2026-03-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(max_length=100, unique=True, verbose_name='商品编码')),
                ('goods_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('goods_unit', models.CharField(max_length=50, verbose_name='商品单位')),
                ('goods_class', models.CharField(max_length=100, verbose_name='商品分类')),
                ('goods_brand', models.CharField(max_length=100, verbose_name='商品品牌')),
                ('goods_origin', models.CharField(blank=True, max_length=100, verbose_name='原产地')),
                ('safety_stock', models.IntegerField(default=0, verbose_name='安全库存')),
                ('goods_desc', models.TextField(blank=True, verbose_name='商品描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'goods',
                'ordering': ['-create_time'],
            },
        ),
    ]
